"""Initial migration

Revision ID: 2476b69bc352
Revises: 
Create Date: 2026-04-04 13:03:30.754189

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '2476b69bc352'
down_revision = None
branch_labels = None
depends_on = None


def data_upgrades():
    """Add any optional data upgrade migrations here!"""

    table = sa.sql.table('categories', sa.sql.column('name', sa.String))

    op.bulk_insert(table,
        [
            {'name': 'Программирование'},
            {'name': 'Математика'},
            {'name': 'Языкознание'},
        ]
    )


def add_courses():
    """Добавление курсов"""
    table = sa.sql.table('courses',
        sa.sql.column('id', sa.Integer),
        sa.sql.column('name', sa.String),
        sa.sql.column('short_desc', sa.String),
        sa.sql.column('full_desc', sa.String),
        sa.sql.column('rating_sum', sa.Integer),
        sa.sql.column('rating_num', sa.Integer),
        sa.sql.column('category_id', sa.Integer),
        sa.sql.column('author_id', sa.Integer),
        sa.sql.column('background_image_id', sa.String),
        sa.sql.column('created_at', sa.DateTime)
    )
    
    op.bulk_insert(table, [
        {
            'id': 1,
            'name': 'Python для начинающих',
            'short_desc': 'Изучите основы программирования на языке Python с нуля',
            'full_desc': 'Курс познакомит вас с основами программирования на Python. Вы узнаете о переменных, типах данных, условных операторах, циклах, функциях и работе с файлами. Курс подходит для абсолютных новичков.',
            'rating_sum': 25,
            'rating_num': 5,
            'category_id': 1,
            'author_id': 1,
            'background_image_id': 'img1',
            'created_at': datetime.now()
        },
        {
            'id': 2,
            'name': 'Веб-разработка на Flask',
            'short_desc': 'Создавайте веб-приложения с помощью микрофреймворка Flask',
            'full_desc': 'Курс по созданию веб-приложений на Flask. Вы научитесь создавать маршруты, работать с шаблонами, формами, базами данных и авторизацией. В конце курса вы создадите полноценное веб-приложение.',
            'rating_sum': 18,
            'rating_num': 4,
            'category_id': 1,
            'author_id': 1,
            'background_image_id': 'img1',
            'created_at': datetime.now()
        },
        {
            'id': 3,
            'name': 'Линейная алгебра',
            'short_desc': 'Изучите основы линейной алгебры для Data Science',
            'full_desc': 'Курс охватывает основные понятия линейной алгебры: векторы, матрицы, определители, системы линейных уравнений. Особое внимание уделяется приложениям в машинном обучении.',
            'rating_sum': 15,
            'rating_num': 3,
            'category_id': 2,
            'author_id': 2,
            'background_image_id': 'img2',
            'created_at': datetime.now()
        },
        {
            'id': 4,
            'name': 'Английский для IT',
            'short_desc': 'Английский язык для программистов и IT-специалистов',
            'full_desc': 'Курс поможет вам освоить профессиональную английскую лексику, необходимую для чтения документации, общения с коллегами и прохождения собеседований в международные компании.',
            'rating_sum': 12,
            'rating_num': 3,
            'category_id': 3,
            'author_id': 2,
            'background_image_id': 'img3',
            'created_at': datetime.now()
        },
        {
            'id': 5,
            'name': 'UX/UI Дизайн',
            'short_desc': 'Основы проектирования пользовательских интерфейсов',
            'full_desc': 'Курс познакомит вас с принципами UX/UI дизайна. Вы узнаете о создании прототипов, проведении пользовательского тестирования, основах типографики и композиции.',
            'rating_sum': 20,
            'rating_num': 4,
            'category_id': 4,
            'author_id': 3,
            'background_image_id': 'img1',
            'created_at': datetime.now()
        },
    ])


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('images',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('md5_hash', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images')),
    sa.UniqueConstraint('md5_hash', name=op.f('uq_images_md5_hash'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_desc', sa.Text(), nullable=False),
    sa.Column('full_desc', sa.Text(), nullable=False),
    sa.Column('rating_sum', sa.Integer(), nullable=False),
    sa.Column('rating_num', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('background_image_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_courses_author_id_users')),
    sa.ForeignKeyConstraint(['background_image_id'], ['images.id'], name=op.f('fk_courses_background_image_id_images')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_courses_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_reviews_course_id_courses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###
    data_upgrades()
    add_courses()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('images')
    op.drop_table('categories')
    # ### end Alembic commands ###
